//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itemLendsSystemV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_lend_items
    {
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string BorowerName { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public Nullable<System.DateTime> ReturnDateExpected { get; set; }
        public Nullable<System.DateTime> ReturnDateActual { get; set; }
    }
}
